services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx
    networks:
      - node-newtwork
    ports:
      - 8080:80
    depends_on:
      - app

  app:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - node-newtwork
    tty: true
    volumes: 
    - ./node:/home/node/app
    ports: 
      - "3000"
    depends_on:
      - db
    command: > 
      bash -c "npm init -y && 
              npm install express --save && 
              npm install mysql --save && 
              node index.js"

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-newtwork


networks:
  node-newtwork:
    driver: bridge
